"""initial schema

Revision ID: dcb31071edb9
Revises: 
Create Date: 2026-09-16 13:22:07.248947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb31071edb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'points_of_sale', ['name'])
    op.create_unique_constraint(None, 'products', ['name'])
    op.create_unique_constraint(None, 'registers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registers', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'points_of_sale', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
